
server:
  port: 8080
spring:
  profiles:
    active: prod
---

server:
  port: 8081
spring:
  profiles: dev

---

server:
  port: 9090

spring:
  profiles: demo

---

server:
  port: 8083

spring:
  profiles: prod
